### PR TITLE
Add nginx conf to include security headers

### PR DESCRIPTION
**Pull request by johnmcmahon**
This is the default nginx.conf as of 1.2.2 with added headers for security reasons.

### CODE REVIEW

**Comment by johnmcmahon** [comment]
Are you guys using Frames at all? I just set X-Frame-Options to DENY but if we need it, it can be SAMEORIGIN

**Comment by dbazile** [comment]
Oooo, shiny!  I might have to tweak some things but this is definitely going to be useful. :+1:

> Are you guys using Frames at all?

No frames. Giving me flashbacks of the GeoCities days. :)

**Comment by johnmcmahon** [comment]
Yep so that is the default nginx.conf that was automatically getting picked up when we deploy using the staticfile buildpack 1.2.2 (any other version should work but i figured I'd start with what was currently being used.

**Comment by dbazile** [comment]
Does it matter what folder the file is in?  It looks like it's in `/conf` for pz-sak.

**Comment by johnmcmahon** [comment]
It's supposed to be in the root (by default).  In sak the one in conf is for development purposes.  But SAK's actual nginx.conf is in public/ (you put it where it will be at the root in the webapp)  public is the root of what gets deployed to nginx because we have a Staticfile at the root of the repo that specifies the root of nignx

**Comment by dbazile** [comment]
Roger.

**Pull request merged**
