### PR TITLE
story/29227

### PR DESCRIPTION
**Pull request by gwbarrett**
Simply comments out the links for product lines.  These are for features that do not yet work.

### CODE REVIEW

**Comment by johnmcmahon** [comment]
This looks good to me

**Comment by johnmcmahon** [comment]
not sure if master is still frozen

**Comment by gwbarrett** [comment]
So what is the procedure?  Do you merge it or does it come back to me to do it?

**Comment by johnmcmahon** [comment]
generally I would go ahead and merge it, i just wasn't sure if it's ok to merge to master (or if this is ATO related and needs to be merged to UC-Stable)

**Comment by gwbarrett** [comment]
@johnmcmahon @mlynum @jphillipsRB

I think we should get this merged into [master](https://github.com/venicegeo/bf-ui/tree/master), unless that affects [UC-Stable](https://github.com/venicegeo/bf-ui/tree/UC-Stable).

If we can merge it then I can mark [story/29227](https://redmine.devops.geointservices.io/issues/29227) complete.

**Pull request merged**
